before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync . s3://test.quze.co --region=us-east-1 --delete
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  detect_encoding: true
  on:
    branch: master

language: node_js
node_js:
  - node
